-- Finishing materials catalog. cost_category is relative within its category.
SET NAMES utf8mb4;

INSERT IGNORE INTO kb_material_catalog
  (category, subcategory, code, name_en, name_ar, usage_en, suitable_rooms, advantages, disadvantages,
   durability, lifespan_years, maintenance_level, cost_category, wet_area_suitable, unit)
VALUES
-- ------------------------------------------------------------------ flooring
('flooring','porcelain','flr_porcelain_60','Porcelain Tile 60x60','بورسلان 60×60','General floors — living, corridors, kitchens, bathrooms',
 '["*"]','["Very hard wearing","Low water absorption (<0.5%)","Stain resistant","Huge design range"]','["Cold/hard underfoot","Skilled cutting needed","Hollow spots if badly bedded"]',
 'very_high',30,'low','standard',1,'m2'),
('flooring','porcelain','flr_porcelain_large','Large-format Porcelain 120x60+','بورسلان مقاسات كبيرة','Premium open areas, feature floors, wall cladding',
 '["living_room","majlis","entrance","corridor","kitchen","bathroom"]','["Minimal grout lines","Luxury look","Book-match marble effects"]','["High cutting waste","Needs very flat screed (±2 mm)","Expensive installation"]',
 'very_high',30,'low','premium',1,'m2'),
('flooring','ceramic','flr_ceramic','Ceramic Tile','سيراميك','Budget floors and walls, service areas',
 '["kitchen","bathroom","laundry","maid_room","storage","balcony"]','["Economical","Easy to source","Easy to cut"]','["Chips at edges","Higher absorption than porcelain","Glaze wears in traffic paths"]',
 'high',20,'low','economy',1,'m2'),
('flooring','natural_stone','flr_marble','Natural Marble','رخام طبيعي','Luxury reception floors, entrances, stairs',
 '["majlis","entrance","living_room","corridor"]','["Prestige finish","Each slab unique","Cool underfoot in hot climate"]','["Etches with acids (lemon, cleaners)","Needs periodic sealing/polishing","Stains if unsealed"]',
 'high',40,'high','luxury',0,'m2'),
('flooring','natural_stone','flr_granite','Granite','جرانيت','Heavy-traffic floors, entrances, external steps',
 '["entrance","corridor","balcony","kitchen"]','["Hardest common stone","Acid and scratch resistant","Outdoor capable"]','["Limited color range","Heavy — check slab loads","Cold appearance"]',
 'very_high',40,'low','premium',1,'m2'),
('flooring','vinyl','flr_spc','SPC Vinyl Click Flooring','أرضيات SPC','Bedrooms, offices, renovation over existing tiles',
 '["master_bedroom","bedroom","kids_room","guest_room","office","dressing_room"]','["100% waterproof core","Installs over old floors","Warm and quiet underfoot","Fast install"]','["Dents under very heavy point loads","Cheap grades fade in direct sun","Feels less premium than wood"]',
 'high',15,'low','standard',1,'m2'),
('flooring','wood','flr_hdf','Laminate (HDF) Parquet','باركيه HDF','Bedrooms and dry living areas on a budget',
 '["master_bedroom","bedroom","guest_room","office"]','["Wood look at low cost","Click install, no glue","Scratch-resistant wear layer"]','["Swells with standing water","Cannot be re-sanded","Hollow sound without good underlay"]',
 'medium',10,'low','economy',0,'m2'),
('flooring','wood','flr_engineered','Engineered Wood','خشب هندسي','Premium bedrooms and living areas',
 '["master_bedroom","living_room","office","dressing_room"]','["Real wood surface","Re-sandable 1-2 times","Stable vs solid wood in AC climate"]','["Expensive","Scratches show","Humidity swings open joints"]',
 'high',25,'medium','luxury',0,'m2'),
('flooring','epoxy','flr_epoxy','Epoxy / Microcement Floor','إيبوكسي / ميكروسمنت','Seamless modern floors, garages, feature areas',
 '["storage","laundry","office"]','["Seamless — no grout","Chemical resistant","Any color"]','["Shows substrate cracks","Skilled applicator critical","Scratches visible on gloss"]',
 'high',15,'medium','premium',1,'m2'),

-- --------------------------------------------------------------------- paint
('paint','emulsion','pnt_matt','Plastic Emulsion (Matt)','دهان بلاستيك مطفي','Ceilings and low-touch walls',
 '["*"]','["Cheap","Hides surface defects","Easy recoat"]','["Marks with scrubbing","Absorbs stains","Not washable"]',
 'medium',7,'medium','economy',0,'m2'),
('paint','emulsion','pnt_washable','Premium Washable Emulsion (Silk/Eggshell)','دهان قابل للغسيل','Living areas, kids rooms, corridors',
 '["living_room","family_room","kids_room","corridor","majlis","entrance","office"]','["Scrubbable","Stain resistant","Soft sheen hides handprints"]','["Sheen highlights wall waviness","Costs 2x matt"]',
 'high',10,'low','standard',0,'m2'),
('paint','specialty','pnt_bathroom','Anti-mold Bathroom Paint','دهان مقاوم للرطوبة والعفن','Bathroom and laundry ceilings/walls above tiles',
 '["bathroom","guest_bathroom","laundry","kitchen"]','["Fungicide additives","Moisture tolerant","Wipeable"]','["Limited colors","Still needs ventilation to perform"]',
 'high',8,'low','standard',1,'m2'),
('paint','enamel','pnt_enamel','Oil / Water-based Enamel','دهان زيت / لاكيه','Doors, frames, metalwork, skirting',
 '["*"]','["Hard washable film","Good edge coverage on wood/metal"]','["Slow recoat","Yellows (oil-based)","Brush marks need skill"]',
 'high',10,'low','standard',1,'m2'),
('paint','texture','pnt_texture','Decorative Texture (Graffiato/Stucco)','دهان ديكوري (جرافياتو/استوكو)','Feature walls, majlis columns, facades',
 '["majlis","living_room","entrance"]','["Hides substrate defects completely","Distinctive finish"]','["Hard to repair invisibly","Collects dust in relief","Applicator-dependent quality"]',
 'high',15,'medium','premium',0,'m2'),
('paint','specialty','pnt_kids_washable','Scrubbable Anti-bacterial Paint','دهان صحي قابل للفرك','Kids rooms, clinics-grade walls',
 '["kids_room","kitchen"]','["Survives crayon/marker cleaning","Anti-bacterial film"]','["Premium price","Limited suppliers"]',
 'high',10,'low','premium',0,'m2'),

-- ------------------------------------------------------------------- ceiling
('ceiling','gypsum','clg_gypsum_flat','Flat Gypsum Board Ceiling','سقف جبس مستوي','Whole-house standard false ceiling',
 '["*"]','["Clean flat finish","Hides MEP services","Fast install"]','["Needs access hatches at valves/units","Cracks at bad joints","Sags if wetted"]',
 'high',20,'low','standard',0,'m2'),
('ceiling','gypsum','clg_gypsum_cove','Tray / Cove Design Gypsum Ceiling','سقف جبس ديكور مع إضاءة مخفية','Living, majlis, master bedroom feature ceilings',
 '["living_room","majlis","master_bedroom","dining_room","entrance"]','["Integrates hidden LED coves","Adds perceived height/luxury","Zoning of large spaces"]','["Costs 1.5-2x flat","Dust shelf in coves","Complicates AC diffuser layout"]',
 'high',20,'medium','premium',0,'m2'),
('ceiling','gypsum','clg_gypsum_mr','Moisture-resistant (Green) Gypsum Board','جبس مقاوم للرطوبة (أخضر)','Bathrooms, kitchens, laundry ceilings',
 '["bathroom","guest_bathroom","kitchen","laundry"]','["Tolerates humidity","Same install as standard board"]','["Not waterproof — still fails under direct leaks","~30% cost premium"]',
 'high',20,'low','standard',1,'m2'),
('ceiling','pvc','clg_pvc','PVC Ceiling Panels','أسقف PVC','Budget wet areas, service rooms',
 '["bathroom","laundry","storage","maid_room"]','["Fully waterproof","Cheap","Demountable for access"]','["Plastic look","Yellows over time","Rattles in AC airflow"]',
 'medium',12,'low','economy',1,'m2'),
('ceiling','acoustic','clg_acoustic','Acoustic Ceiling Tiles 60x60','بلاط أسقف صوتي','Home office, media rooms',
 '["office"]','["Sound absorption","Full service access","Cheap replacement"]','["Office look","Low ceilings feel commercial"]',
 'medium',15,'low','standard',0,'m2'),
('ceiling','stretch','clg_stretch','Stretch Ceiling (Barrisol-type)','سقف فرنسي مشدود','Luxury feature ceilings, backlit panels',
 '["majlis","living_room","dining_room"]','["Perfect seamless surface","Backlit translucent options","No cracking"]','["Specialist installer only","Punctures are fatal","Expensive"]',
 'high',15,'low','luxury',1,'m2'),

-- ------------------------------------------------------------------ lighting
('lighting','downlight','lgt_led_downlight','Recessed LED Downlight 7-9W','سبوت لايت LED مسقط','General ambient layer in gypsum ceilings',
 '["*"]','["Efficient (100+ lm/W)","Clean ceiling","Cheap to replace"]','["Glare if wrong UGR/beam","Cheap drivers flicker","Fixed direction"]',
 'high',8,'low','economy',0,'pc'),
('lighting','strip','lgt_led_strip','LED Strip (COB, 24V)','شريط LED خفي','Coves, under-cabinet, niches, mirrors',
 '["*"]','["Continuous line of light","Dimmable","Dot-free COB versions"]','["Driver placement needs access","Cheap strips color-shift within a year","Visible dots on budget SMD"]',
 'medium',6,'medium','standard',0,'m'),
('lighting','decorative','lgt_chandelier','Chandelier','ثريا','Majlis, dining, double-height entrances',
 '["majlis","dining_room","living_room","entrance"]','["Statement centerpiece","Sets the room style"]','["Cleaning burden","Needs rated ceiling anchor","Often over-scaled for room"]',
 'high',20,'high','premium',0,'pc'),
('lighting','decorative','lgt_pendant','Pendant Light','دلاية إضاءة','Over dining tables, kitchen islands, bedsides',
 '["dining_room","kitchen","master_bedroom"]','["Task + decor in one","Frees bedside table space"]','["Fixed position — must match furniture plan exactly"]',
 'high',15,'low','standard',0,'pc'),
('lighting','track','lgt_magnetic_track','Magnetic Track System 48V','مسار مغناطيسي','Modern living areas, galleries, dressing rooms',
 '["living_room","dressing_room","corridor","office"]','["Reconfigurable fixtures","Mix spot/linear/pendant on one track","Minimal ceiling cuts"]','["Ecosystem lock-in","Premium price","Recessed track needs 5+ cm gypsum depth"]',
 'high',12,'low','luxury',0,'m'),
('lighting','wall','lgt_sconce','Wall Sconce','إضاءة جدارية','Bedheads, corridors, bathroom mirrors',
 '["master_bedroom","corridor","bathroom","majlis"]','["Layered light at eye level","Frees ceiling"]','["Wiring must be planned before plaster","Fixed height forever"]',
 'high',15,'low','standard',0,'pc'),

-- --------------------------------------------------------------------- doors
('doors','wood_solid','dor_solid_wood','Solid Wood Door','باب خشب صلب','Entrance-grade and premium internal doors',
 '["entrance","majlis","master_bedroom"]','["Best acoustics and feel","Re-finishable many times","Prestige"]','["Warps if humidity uncontrolled","Heavy — 4 hinges","Expensive"]',
 'very_high',40,'medium','luxury',0,'pc'),
('doors','mdf','dor_mdf_lacquer','MDF Lacquered Door','باب MDF دوكو','Standard internal doors with painted finish',
 '["master_bedroom","bedroom","kids_room","office","guest_room"]','["Perfectly smooth modern finish","Any RAL color","Stable core"]','["Chips at edges show brown core","Lacquer scratches","Not for wet areas"]',
 'high',15,'medium','standard',0,'pc'),
('doors','hdf','dor_hdf_skin','HDF Skin Moulded Door','باب HDF مضغوط','Budget internal doors',
 '["bedroom","maid_room","storage"]','["Cheapest hinged door","Light weight","Pre-primed"]','["Hollow feel and sound","Puncture-prone","Limited designs"]',
 'medium',10,'low','economy',0,'pc'),
('doors','wpc','dor_wpc','WPC / PVC Door','باب WPC مقاوم للماء','Bathrooms, laundries — all wet areas',
 '["bathroom","guest_bathroom","laundry"]','["100% waterproof","Never swells","Termite-proof"]','["Plastic feel","Limited premium finishes","Weak screw-holding for heavy hardware"]',
 'high',20,'low','standard',1,'pc'),
('doors','aluminum','dor_aluminum','Aluminum Door (glazed)','باب ألمنيوم','Balconies, external service doors',
 '["balcony","laundry","kitchen"]','["Weatherproof","Zero maintenance","Slim sightlines"]','["Thermal bridging unless broken profile","Rattles if cheap profile"]',
 'very_high',30,'low','standard',1,'pc'),
('doors','glass','dor_glass','Frameless Glass Door','باب زجاج سيكوريت','Office fronts, shower enclosures, internal features',
 '["office","bathroom"]','["Light transmission","Modern look"]','["No acoustic privacy","Fingerprint maintenance","Tempered only — cannot re-cut"]',
 'high',20,'medium','premium',1,'pc'),
('doors','steel','dor_security','Security Steel Entrance Door','باب حديد أمان','Apartment entrance doors',
 '["entrance"]','["Security rating","Fire options","Acoustic seals"]','["Industrial look unless clad","Heavy on frame anchors"]',
 'very_high',30,'low','premium',0,'pc'),

-- ------------------------------------------------------------------ kitchens
('kitchens','carcass','kit_mdf_thermofoil','MDF Thermofoil (PVC-wrapped) Kitchen','مطبخ MDF ملفوف PVC','Budget-to-standard kitchen cabinets',
 '["kitchen"]','["Economical","Seamless wrapped edges","Easy cleaning"]','["Foil peels near ovens/steam","Limited to matte/gloss basics"]',
 'medium',10,'low','economy',1,'lm'),
('kitchens','carcass','kit_acrylic','High-gloss Acrylic Kitchen','مطبخ أكريليك','Modern gloss kitchens',
 '["kitchen"]','["Mirror-gloss finish","UV stable colors","Scratch-buffable"]','["Shows fingerprints","Edge banding quality critical"]',
 'high',15,'low','standard',1,'lm'),
('kitchens','carcass','kit_lacquer','Lacquered (Duco) Kitchen','مطبخ دوكو','Custom-color premium kitchens',
 '["kitchen"]','["Any color/sheen","Repairable by respray","Handle-less designs"]','["Chips on impact","Costly skilled finishing"]',
 'high',15,'medium','premium',1,'lm'),
('kitchens','carcass','kit_hpl','HPL / Compact Laminate Kitchen','مطبخ HPL','Heavy-use family kitchens',
 '["kitchen"]','["Most impact/scratch resistant front","Heat tolerant","Realistic wood textures"]','["Visible edge lines unless laser-edged"]',
 'high',20,'low','standard',1,'lm'),
('kitchens','countertop','kit_top_granite','Granite Countertop','سطح جرانيت','Standard worktops',
 '["kitchen"]','["Heat-proof","Scratch resistant","Natural stone price now moderate"]','["Needs sealing yearly","Seams visible","Limited whites"]',
 'very_high',30,'medium','standard',1,'lm'),
('kitchens','countertop','kit_top_quartz','Engineered Quartz Countertop','سطح كوارتز صناعي','Premium worktops',
 '["kitchen"]','["Non-porous — no sealing","Consistent color","Stain-proof"]','["Scorches above ~150°C — use trivets","Premium price"]',
 'very_high',25,'low','premium',1,'lm'),
('kitchens','countertop','kit_top_solid_surface','Solid Surface (Corian-type)','سطح أكريليك صب','Seamless tops with integrated sinks',
 '["kitchen","bathroom"]','["Invisible seams","Integrated molded sinks","Repairable by sanding"]','["Scratches and scorches easily","Softer than stone"]',
 'high',20,'medium','premium',1,'lm'),

-- ------------------------------------------------------------------ sanitary
('sanitary','wc','san_wallhung_wc','Wall-hung WC + Concealed Cistern','كرسي معلق مع صندوق مخفي','Modern bathrooms',
 '["bathroom","guest_bathroom"]','["Easy floor cleaning under bowl","Adjustable height","Silent premium flush plates"]','["Carrier + cistern cost 2-3x floor WC","Access only via flush plate","Repairs need parts availability"]',
 'high',25,'medium','premium',1,'pc'),
('sanitary','wc','san_floor_wc','Floor-standing WC (back-to-wall)','كرسي أرضي','Standard bathrooms',
 '["bathroom","guest_bathroom","maid_room"]','["Cheapest reliable option","All parts serviceable","No carrier frame"]','["Cleaning around base","Visible cistern"]',
 'very_high',30,'low','economy',1,'pc'),
('sanitary','basin','san_counter_basin','Countertop Vessel Basin','مغسلة فوق الرخامة','Feature guest bathrooms and master vanities',
 '["bathroom","guest_bathroom"]','["Design statement","Any counter material below"]','["Splash if too shallow","Tall mixer required","Harder to clean junction"]',
 'high',20,'medium','premium',1,'pc'),
('sanitary','basin','san_under_counter','Under-counter Basin','مغسلة تحت الرخامة','Family bathrooms — easiest cleaning',
 '["bathroom"]','["Counter wipes straight into basin","Concealed rim"]','["Needs stone/quartz counter","Mounting failure risk with bad adhesive"]',
 'high',20,'low','standard',1,'pc'),
('sanitary','basin','san_pedestal','Pedestal Basin','مغسلة بعمود','Budget bathrooms',
 '["guest_bathroom","maid_room"]','["Cheap","Hides trap"]','["Zero counter space","Fixed height"]',
 'high',25,'low','economy',1,'pc'),
('sanitary','bath','san_acrylic_tub','Acrylic Bathtub','بانيو أكريليك','Family and kids bathrooms',
 '["bathroom"]','["Warm to touch","Light weight","Repairable surface"]','["Flexes — needs full mortar bed","Scratches with abrasives"]',
 'medium',15,'low','standard',1,'pc'),
('sanitary','shower','san_shower_tray','Stone-resin Shower Tray','قاعدة دش','Shower enclosures',
 '["bathroom","guest_bathroom"]','["Anti-slip textures","Low profile 3-4 cm","Pre-formed slope"]','["Heavy","Cutting to size difficult"]',
 'high',20,'low','standard',1,'pc'),
('sanitary','mixer','san_mixer_brass','Brass Mixer (ceramic cartridge)','خلاط نحاس','All wet points',
 '["bathroom","guest_bathroom","kitchen","laundry"]','["25+ year body life","Cartridge cheap to swap","Finish options (chrome/matte/gold)"]','["Cheap clones corrode from inside — verify brass weight","PVD finishes scratch"]',
 'very_high',25,'low','standard',1,'pc'),
('sanitary','mixer','san_thermostatic','Thermostatic Shower Mixer','خلاط حراري ثابت','Kids and elderly bathrooms — anti-scald',
 '["bathroom"]','["Locks temperature — no scald","Comfort on pressure fluctuation"]','["2-3x price","Cartridge sensitive to debris — needs filters"]',
 'high',15,'medium','premium',1,'pc'),
('sanitary','accessory','san_concealed_valve','Concealed Angle Valves + Manifold','محابس مخفية مع مجمع','Luxury distribution — one shutoff per fixture',
 '["bathroom","kitchen","laundry"]','["Per-fixture isolation","Leak localization","Clean look"]','["Access panel mandatory","Higher rough-in cost"]',
 'high',25,'low','luxury',1,'pc');
