-- Construction progress stages. weight_pct sums to 100 within each trade so
-- trade progress = Σ(completed stage weights). `dependencies` reference stage
-- codes across trades — the sequencing engine treats them as blocking.
SET NAMES utf8mb4;

INSERT IGNORE INTO kb_construction_stages
  (trade, code, name_en, name_ar, sequence, weight_pct, definition_en,
   checklist, completion_criteria, dependencies, required_materials, required_photos, inspection_items)
VALUES
-- ------------------------------------------------------------------ plumbing
('plumbing','plb_drain_rough','Drainage Rough-in','تأسيس الصرف',1,30.00,
 'Install all drainage pipes, floor drain bodies and WC collars inside slabs/walls before any covering work.',
 '[{"key":"routes","text_en":"Pipe routes match approved plumbing layout"},{"key":"slope","text_en":"Horizontal runs sloped 2% (pipes <= 110 mm)"},{"key":"fd_position","text_en":"Floor drains at lowest point of planned floor slope"},{"key":"vent","text_en":"Vent pipes connected and extended to riser/roof"},{"key":"protection","text_en":"Open pipe ends capped against debris"}]',
 '["All drainage points from layout exist on site","Water test held 24h with no level drop","Site engineer sign-off recorded"]',
 '[]',
 '["pvc_drainage_pipe","pipe_fittings","floor_drain_bodies"]',
 '[{"key":"routes_open","description_en":"All drainage routes photographed before covering","min_count":4},{"key":"water_test","description_en":"Filled stack/water test in progress","min_count":1}]',
 '["Slope verified with level on every horizontal run","Joint solvent welds continuous","No sharp 90° bends on horizontal WC runs (use 45° pairs)"]'),

('plumbing','plb_supply_rough','Water Supply Rough-in','تأسيس التغذية',2,25.00,
 'Install PPR/PEX hot and cold supply lines, manifolds and angle-valve points to every fixture position.',
 '[{"key":"points","text_en":"Every fixture from kb_plumbing_standards has supply points at listed heights"},{"key":"hot_left","text_en":"Hot line on the left of each point pair"},{"key":"insulation","text_en":"Hot lines insulated along full run"},{"key":"spacing","text_en":"Point pairs 15-20 cm apart, level"}]',
 '["All points match fixture schedule","Lines anchored every 1 m","No joints buried without test"]',
 '["plb_drain_rough"]',
 '["ppr_pipe","ppr_fittings","pipe_insulation"]',
 '[{"key":"walls_open","description_en":"Supply routes in every wet wall before plaster","min_count":4}]',
 '["Heights match standard (basin 55-60, shower mixer 100-110, WC/shattaf 60)","Crossovers use bridge fittings, not stacked pipes"]'),

('plumbing','plb_pressure_test','Pressure Test','اختبار الضغط',3,10.00,
 'Pressurize supply network to 1.5x working pressure (min 10 bar) and hold to prove joint integrity before covering.',
 '[{"key":"gauge","text_en":"Calibrated gauge installed at manifold"},{"key":"pressure","text_en":"System pumped to 10 bar minimum"},{"key":"hold","text_en":"Pressure held 24 hours"},{"key":"record","text_en":"Start/end readings photographed with timestamps"}]',
 '["Pressure drop <= 0.2 bar over 24h","Test certificate uploaded","Consultant/engineer witness recorded"]',
 '["plb_supply_rough"]',
 '["test_pump","pressure_gauge"]',
 '[{"key":"gauge_start","description_en":"Gauge at test start with visible reading","min_count":1},{"key":"gauge_end","description_en":"Gauge after 24h with visible reading","min_count":1}]',
 '["Gauge calibration valid","All branch valves open during test","Result recorded against unit, not project only"]'),

('plumbing','plb_fixtures','Fixture Installation','تركيب الأدوات الصحية',4,25.00,
 'Install sanitary ware, mixers, accessories and connect to tested rough-in points.',
 '[{"key":"level","text_en":"Basins/WCs level and sealed with sanitary silicone"},{"key":"clearances","text_en":"Installed positions respect clearance standards"},{"key":"traps","text_en":"All traps installed and holding water seal"},{"key":"heater","text_en":"Water heaters mounted with drain pan piped"}]',
 '["Every fixture operates without leak at full pressure","Silicone joints continuous and tooled","Protective films removed only after handover cleaning"]',
 '["plb_pressure_test","flr_tiling"]',
 '["sanitary_ware","mixers","silicone","traps"]',
 '[{"key":"per_fixture","description_en":"Each installed fixture, connections visible","min_count":6}]',
 '["No flexible hose under permanent tension","Wall-hung WC torque per carrier spec","Angle valves accessible, not painted over"]'),

('plumbing','plb_final_test','Final Test & Commissioning','الاختبار النهائي والتشغيل',5,10.00,
 'Full-system operational test: flow, drainage speed, hot water delivery, leak audit under use conditions.',
 '[{"key":"flow","text_en":"Every outlet delivers steady flow, both temperatures"},{"key":"drain_speed","text_en":"Basins/showers drain without pooling"},{"key":"hot_delivery","text_en":"Hot water reaches farthest outlet in acceptable time"},{"key":"leak_audit","text_en":"Cabinet interiors and ceilings dry after 48h of use"}]',
 '["Zero active leaks","Drainage odor traps sealed","Handover checklist signed"]',
 '["plb_fixtures"]',
 '[]',
 '[{"key":"commissioning","description_en":"Running outlets during test","min_count":3}]',
 '["Check under-sink cabinets with dry tissue","Confirm floor drains hold water seal","Water heater relief valve discharges to drain"]'),

-- ---------------------------------------------------------------- electrical
('electrical','ele_conduits','Conduits & Boxes','تأسيس المواسير والعلب',1,25.00,
 'Chase walls/slabs, install conduits and back boxes for all points per the approved electrical layout.',
 '[{"key":"positions","text_en":"Box positions/heights match kb_electrical_standards"},{"key":"separation","text_en":"Power and data conduits separated (min 20 cm parallel runs)"},{"key":"radius","text_en":"Bends use springs/long radius — no crushed conduits"},{"key":"boxes_level","text_en":"Back boxes flush with finished plaster plane, level"}]',
 '["Point count per room >= layout count","Draw wires present in every conduit","Chases closed with mortar, not gypsum"]',
 '[]',
 '["pvc_conduit","back_boxes","draw_wire"]',
 '[{"key":"walls_open","description_en":"Conduited walls per room before plaster","min_count":4}]',
 '["Socket boxes at 30 cm, switches 110 cm, counter sockets 110 cm","Kitchen appliance circuits have their own conduits","Bathroom boxes outside shower splash zone"]'),

('electrical','ele_wiring','Cable Pulling','سحب الأسلاك',2,25.00,
 'Pull all circuits: lighting 2x1.5 + E, sockets 2x2.5 + E, AC/heater per dedicated schedule, data cat6.',
 '[{"key":"sizes","text_en":"Cable sizes match circuit schedule (1.5 lighting / 2.5 sockets / 4-6 AC-oven)"},{"key":"earth","text_en":"Earth conductor present in every circuit"},{"key":"color_code","text_en":"Consistent phase/neutral/earth colors throughout"},{"key":"slack","text_en":"15-20 cm slack coiled in each box"}]',
 '["Continuity test passed per circuit","No joints inside conduits — junctions only in boxes","Circuit register filled (room → breaker)"]',
 '["ele_conduits"]',
 '["cable_1_5mm","cable_2_5mm","cable_4mm","cable_6mm","cat6_cable"]',
 '[{"key":"db_tails","description_en":"Labeled circuit tails at DB","min_count":1},{"key":"box_slack","description_en":"Sample boxes with coiled slack","min_count":3}]',
 '["Megger insulation test >= 1 MΩ per circuit","Data cables untwisted <13 mm at terminations","No power/data sharing a box without divider"]'),

('electrical','ele_db','Distribution Board & Breakers','لوحة التوزيع والقواطع',3,15.00,
 'Install DB, RCDs and breakers; terminate and label every circuit.',
 '[{"key":"rcd","text_en":"RCD 30 mA protection on socket and wet-area circuits"},{"key":"sizing","text_en":"Breaker ratings match cable sizes (16A/2.5mm², 20A/4mm², 32A/6mm²)"},{"key":"labels","text_en":"Every breaker labeled in Arabic + English"},{"key":"balance","text_en":"Loads balanced across phases (3-phase supplies)"}]',
 '["Torque check on all terminals","Main earth bar connected to earthing system","DB schedule card printed and fixed inside door"]',
 '["ele_wiring"]',
 '["distribution_board","breakers","rcd_units"]',
 '[{"key":"db_finished","description_en":"Completed DB with labels visible","min_count":2}]',
 '["RCD test button trips correctly","No double-lugged breakers","Spare ways >= 20%"]'),

('electrical','ele_accessories','Switches & Sockets Installation','تركيب المفاتيح والأفياش',4,20.00,
 'Fit final wiring accessories, plates, and smart devices after painting final coat.',
 '[{"key":"level","text_en":"Plates level and flush, no plaster gaps"},{"key":"polarity","text_en":"Correct polarity at every socket (tester)"},{"key":"smart_neutral","text_en":"Smart switches have neutral at the box"},{"key":"shuttered","text_en":"Child-safe shuttered sockets in kids rooms"}]',
 '["Every point from layout is fitted and functional","Two-way circuits switch from both ends","USB outlets deliver rated current"]',
 '["ele_db","pnt_final"]',
 '["switches","sockets","smart_devices","usb_outlets"]',
 '[{"key":"per_room","description_en":"Accessory walls per room after fit","min_count":4}]',
 '["Socket tester on 100% of sockets","Dimmers matched to LED load type","Plate alignment across vertical stacks"]'),

('electrical','ele_test','Testing & Certification','الفحص والاختبار النهائي',5,15.00,
 'Full installation test: insulation, earth loop, RCD times, functional test of every point; issue completion certificate.',
 '[{"key":"insulation","text_en":"Insulation resistance recorded per circuit"},{"key":"earth_loop","text_en":"Earth loop impedance within breaker disconnect limits"},{"key":"rcd_time","text_en":"RCD trip times <= 300 ms at 1x, <= 40 ms at 5x"},{"key":"functional","text_en":"Every light, socket and smart device operated"}]',
 '["Test sheet uploaded with instrument readings","Zero outstanding electrical snags","Certificate signed by qualified electrician"]',
 '["ele_accessories"]',
 '[]',
 '[{"key":"instrument","description_en":"Test instrument readings during test","min_count":2}]',
 '["Readings match circuit register","Verify labels against actual rooms","Confirm isolation switches for AC/heaters function"]'),

-- ---------------------------------------------------------------------- hvac
('hvac','hvac_pipe_rough','Refrigerant Piping & Drain Rough-in','تأسيس مواسير التكييف والصرف',1,35.00,
 'Run insulated refrigerant pairs, condensate drains (sloped) and power provisions from indoor unit positions to outdoor locations.',
 '[{"key":"insulation","text_en":"Suction and liquid lines individually insulated, joints taped"},{"key":"drain_slope","text_en":"Condensate drain slope >= 1% to approved discharge"},{"key":"trap","text_en":"Condensate trap at unit per manufacturer"},{"key":"lengths","text_en":"Pipe lengths within unit max run/lift limits"}]',
 '["Drain lines water-tested before ceiling closes","Pipe ends sealed and pressurized with holding charge/nitrogen","Routes photographed before covering"]',
 '[]',
 '["copper_pipe_pair","pipe_insulation","condensate_pipe"]',
 '[{"key":"routes","description_en":"Pipe and drain routes above ceiling line","min_count":3},{"key":"drain_test","description_en":"Water poured in drain pan/line during test","min_count":1}]',
 '["No kinked copper bends","Drain does not tie into soil stack without trap/air gap","Wall sleeves sealed"]'),

('hvac','hvac_ducting','Ducting & Grilles Rough-in (concealed units)','تأسيس الدكت والشبكات',2,25.00,
 'Install supply/return ducting, dampers and grille frames for concealed duct units.',
 '[{"key":"sizing","text_en":"Duct sizes match design airflow"},{"key":"insulation","text_en":"Ducts insulated/lined, joints sealed with mastic"},{"key":"return_path","text_en":"Return air path sized — no starved returns"},{"key":"access","text_en":"Access panels at dampers, coils and drain pans"}]',
 '["Grille frame positions coordinated with gypsum design","No flexible duct runs > 1.5 m or crushed bends","Leak check at joints"]',
 '["hvac_pipe_rough"]',
 '["duct_sheets","duct_insulation","grilles_dampers"]',
 '[{"key":"ducts_open","description_en":"Duct network before ceiling boarding","min_count":3}]',
 '["Coordination with lighting layout signed","Fire damper where duct crosses rated walls","Return grille not opposite supply (short-circuit airflow)"]'),

('hvac','hvac_units','Unit Installation','تركيب الوحدات',3,25.00,
 'Mount indoor/outdoor units, vacuum lines, release/charge refrigerant, connect drains and controls.',
 '[{"key":"vacuum","text_en":"System vacuumed to <= 500 microns and held"},{"key":"mounting","text_en":"Outdoor unit on anti-vibration mounts with service clearance"},{"key":"charge","text_en":"Refrigerant charge per line-length calculation"},{"key":"thermostat","text_en":"Thermostats mounted 150 cm, away from supply air draft"}]',
 '["Vacuum decay test recorded","Condensate flows at unit with test pour","Controls respond from thermostat"]',
 '["hvac_pipe_rough","hvac_ducting"]',
 '["ac_units","refrigerant","thermostats"]',
 '[{"key":"vacuum_gauge","description_en":"Micron gauge reading during vacuum","min_count":1},{"key":"units_mounted","description_en":"Indoor and outdoor units installed","min_count":2}]',
 '["Flare torque per spec — no flare paste as leak fix","Outdoor discharge clearance >= 60 cm","Drain pan clean of construction debris"]'),

('hvac','hvac_commission','Testing & Commissioning','التشغيل والفحص',4,15.00,
 'Run all units at design load; verify temperatures, airflow, drainage and noise before ceiling close-out sign-off.',
 '[{"key":"delta_t","text_en":"Supply/return ΔT within 8-12°C at steady state"},{"key":"airflow","text_en":"All grilles deliver design airflow"},{"key":"drain_full","text_en":"Continuous drain test — 30 min run with dry ceiling"},{"key":"noise","text_en":"No abnormal vibration/noise at any speed"}]',
 '["Commissioning sheet with readings uploaded","Client walkthrough of thermostat use done"]',
 '["hvac_units","ele_db"]',
 '[]',
 '[{"key":"readings","description_en":"Thermometer/anemometer readings","min_count":2}]',
 '["Amp draw vs nameplate","Insulation continuous at unit connections (no sweating)","Filters clean at handover"]'),

-- ---------------------------------------------------------------- plastering
('plastering','pls_prep','Surface Prep & Screeds (Bull Marks)','التجهيز والبؤج والأوتار',1,20.00,
 'Clean substrate, fix mesh at material junctions, set plumb screed points and bands defining the finished plaster plane.',
 '[{"key":"mesh","text_en":"Galvanized mesh over chases and block/concrete junctions"},{"key":"bull_marks","text_en":"Screed points plumb and aligned wall-to-wall"},{"key":"spatterdash","text_en":"Spatterdash/bonding coat on smooth concrete"},{"key":"mep_closed","text_en":"All MEP chases closed and inspected before plaster"}]',
 '["Plumb check every wall <= 5 mm total deviation","Right angles verified at corners (3-4-5)"]',
 '["ele_conduits","plb_supply_rough"]',
 '["cement","sand","plaster_mesh"]',
 '[{"key":"mesh_chases","description_en":"Mesh over closed chases","min_count":3}]',
 '["No plaster over untested plumbing lines","Door/window opening dimensions rechecked against schedule"]'),

('plastering','pls_plaster','Cement Plastering','البياض / اللياسة',2,60.00,
 'Apply cement plaster coats to walls and ceilings to screed plane; internal 15-20 mm typical.',
 '[{"key":"thickness","text_en":"Thickness 15-20 mm; over 25 mm applied in two coats with mesh"},{"key":"flatness","text_en":"2 m straightedge gap <= 3 mm anywhere"},{"key":"corners","text_en":"External corners with corner beads, crisp arris"},{"key":"openings","text_en":"Reveals square and even around doors/windows"}]',
 '["Full coverage, no hollow-sounding areas on tap test","Openings match carpentry schedule ±5 mm"]',
 '["pls_prep"]',
 '["cement","sand","corner_beads"]',
 '[{"key":"walls_done","description_en":"Finished plaster per room","min_count":4}]',
 '["Tap survey for hollows","Straightedge and plumb spot checks","No cracks at junction mesh zones"]'),

('plastering','pls_cure','Curing & Crack Repair','المعالجة وإصلاح الشروخ',3,20.00,
 'Water-cure plaster 3-7 days, then survey and repair shrinkage cracks before any painting starts.',
 '[{"key":"curing","text_en":"Walls wetted 2x daily for min 3 days (climate-adjusted)"},{"key":"survey","text_en":"Crack survey after 7 days, marked on walls"},{"key":"repair","text_en":"Cracks raked and refilled, hollows re-done"}]',
 '["No active cracking two weeks after repair","Moisture content < 12% before paint (protimeter)"]',
 '["pls_plaster"]',
 '["cement"]',
 '[{"key":"curing","description_en":"Curing in progress","min_count":1}]',
 '["Moisture reading logged per room","Repairs flush after drying"]'),

-- -------------------------------------------------------------------- gypsum
('gypsum','gyp_framing','Ceiling Framing','هيكل الأسقف الجبسية',1,30.00,
 'Set out ceiling levels and install channels/hangers per the approved ceiling design, coordinated with all above-ceiling services.',
 '[{"key":"level","text_en":"Perimeter level lasered; design heights per drawing"},{"key":"hangers","text_en":"Hangers max 120 cm spacing, anchored to slab (never to ducts/pipes)"},{"key":"coordination","text_en":"Frame openings for AC grilles, curtains, access hatches set out"},{"key":"cove_depth","text_en":"Cove/tray dimensions fit LED strip + driver access"}]',
 '["MEP above ceiling tested and signed BEFORE closing starts","Frame rigid — no deflection under hand pressure"]',
 '["hvac_pipe_rough","hvac_ducting","ele_wiring","plb_pressure_test"]',
 '["gi_channels","hangers_anchors"]',
 '[{"key":"frame_services","description_en":"Frame with services above, before boarding","min_count":4}]',
 '["Nothing suspended from HVAC/plumbing","Curtain box width fits track type (min 15 cm single, 20 cm double)"]'),

('gypsum','gyp_boarding','Boarding','تركيب الألواح',2,35.00,
 'Fix gypsum boards, moisture-resistant grade in wet areas, staggered joints, screwed at 15-20 cm.',
 '[{"key":"board_grade","text_en":"Green (MR) board in bathrooms, kitchen, laundry"},{"key":"stagger","text_en":"Board joints staggered, no cross joints"},{"key":"screws","text_en":"Screws at 15-20 cm, heads dimpled not broken through paper"},{"key":"cutouts","text_en":"Downlight/grille cutouts per lighting layout, clean holes"}]',
 '["All boards fixed, no unsupported edges","Access hatches installed at every concealed valve/unit"]',
 '["gyp_framing"]',
 '["gypsum_board","mr_gypsum_board","screws"]',
 '[{"key":"boarded","description_en":"Boarded ceilings per room","min_count":4}]',
 '["MR board verified by edge color in wet rooms","Hatch positions match valve/AC locations"]'),

('gypsum','gyp_taping','Taping & Finishing','المعجون والفواصل',3,25.00,
 'Tape joints, fill fastener heads, finish to Level 4 (Level 5 skim where grazing light or gloss paint planned).',
 '[{"key":"tape","text_en":"All joints taped (paper/fiber), corners beaded"},{"key":"coats","text_en":"Three-coat system, sanded between coats"},{"key":"level5","text_en":"Skim coat where cove lighting washes the surface"}]',
 '["No visible joints under raking light test","Surface dust-free ready for primer"]',
 '["gyp_boarding"]',
 '["joint_compound","joint_tape"]',
 '[{"key":"raking_light","description_en":"Raking-light check of finished ceiling","min_count":2}]',
 '["Raking light (LED held flat to surface) shows no ridges","Cove internal corners crisp and straight"]'),

('gypsum','gyp_hatches','Access Hatches & Final Openings','فتحات الصيانة والتشطيب',4,10.00,
 'Install access panels, verify every concealed serviceable item is reachable, cut any missed openings.',
 '[{"key":"map","text_en":"Hatch map cross-checked against valve/unit register"},{"key":"size","text_en":"Hatches min 30x30 cm (60x60 at AC units/heaters)"},{"key":"fit","text_en":"Panels flush, paintable, gasketed in wet areas"}]',
 '["Every angle valve, damper, driver and heater reachable","Hatch schedule photographed and archived"]',
 '["gyp_taping"]',
 '["access_panels"]',
 '[{"key":"hatches","description_en":"Each installed hatch open + closed","min_count":3}]',
 '["Open every hatch and touch the item it serves","LED drivers not sealed inside coves without access"]'),

-- ------------------------------------------------------------------ flooring
('flooring','flr_waterproof','Waterproofing (Wet Areas)','العزل المائي',1,20.00,
 'Apply waterproof membrane to wet-area floors and walls (min 30 cm up walls; 180 cm in shower zones), then flood test.',
 '[{"key":"prep","text_en":"Substrate clean, cracks pre-filled, corners coved/taped"},{"key":"coats","text_en":"Two coats applied in perpendicular directions"},{"key":"upstands","text_en":"30 cm wall upstand; 180 cm in shower wet wall; door threshold wrapped"},{"key":"flood","text_en":"48h flood test with marked water level"}]',
 '["Zero level drop and no dampness below after 48h","Membrane continuous at drains (clamped/collared)"]',
 '["plb_drain_rough","plb_pressure_test"]',
 '["waterproof_membrane","corner_tape"]',
 '[{"key":"membrane","description_en":"Membrane coverage incl. upstands before test","min_count":3},{"key":"flood_test","description_en":"Flood test with level mark, start and end","min_count":2}]',
 '["Puncture check before covering","Drain collar integration correct","Test result recorded per room"]'),

('flooring','flr_screed','Screed & Levels','اللياسة الأرضية والمناسيب',2,20.00,
 'Lay leveling screed to design FFL minus finish thickness; fall to drains in wet areas.',
 '[{"key":"levels","text_en":"FFL datum transferred to every room; screed = FFL - finish build-up"},{"key":"falls","text_en":"Wet areas fall 1.5-2% to floor drains, verified with water"},{"key":"flatness","text_en":"3 mm / 2 m for large-format tile zones"},{"key":"cure","text_en":"Cured min 7 days before tiling"}]',
 '["Water poured at door reaches drain in every wet room","No cracking/hollowness after cure"]',
 '["flr_waterproof"]',
 '["cement","sand"]',
 '[{"key":"falls_test","description_en":"Water flow test toward drain","min_count":2}]',
 '["Straightedge survey logged","Thickness min 25 mm bonded / 50 mm unbonded"]'),

('flooring','flr_tiling','Tiling / Floor Finish Installation','تركيب البلاط والأرضيات',3,40.00,
 'Install tile/stone/wood floors per layout drawings: centered layouts, aligned joints, full adhesive coverage.',
 '[{"key":"layout","text_en":"Dry-lay approved: centered on room or per drawing, cuts balanced at edges"},{"key":"coverage","text_en":"Back-buttered large formats; >= 90% adhesive coverage (lift test)"},{"key":"lippage","text_en":"Lippage <= 1 mm (leveling clips on large format)"},{"key":"joints","text_en":"Joint width consistent (2-3 mm rectified); expansion joints at 25 m² fields and doorways"},{"key":"protection","text_en":"Finished floors boarded/covered immediately"}]',
 '["Tap test: no hollow tiles (max 5% corner hollowness tolerated)","Joints aligned through doorways where drawings require"]',
 '["flr_screed","pls_cure"]',
 '["floor_tiles","tile_adhesive","leveling_clips"]',
 '[{"key":"dry_lay","description_en":"Approved dry-lay/setting-out","min_count":1},{"key":"finished","description_en":"Finished floor per room","min_count":4}]',
 '["Random lift test at start of work","Slope preserved to drains after tiling","Wood/SPC expansion gaps at perimeter 8-10 mm"]'),

('flooring','flr_grout_skirt','Grouting & Skirting','الترويب والنعلات',4,20.00,
 'Grout joints, seal movement joints with matching sealant, install skirting.',
 '[{"key":"grout","text_en":"Joints full and flush, color per approval, cleaned before cure"},{"key":"silicone","text_en":"Silicone (not grout) at all floor-wall junctions in wet areas"},{"key":"skirting","text_en":"Skirting level, scribed to floor, mitred corners"}]',
 '["No grout voids on raking inspection","Skirting-to-wall gap caulked ready for paint touch-up"]',
 '["flr_tiling"]',
 '["grout","silicone","skirting"]',
 '[{"key":"detail","description_en":"Grout and skirting details at corners","min_count":3}]',
 '["Wet-area junctions flexible-sealed","Grout sealed on natural stone"]'),

-- ------------------------------------------------------------------ painting
('painting','pnt_putty','Putty / Skim Coats','المعجون',1,30.00,
 'Apply 2-3 putty coats to plaster and gypsum, sanding between coats to a defect-free plane.',
 '[{"key":"moisture","text_en":"Substrate moisture < 12% before starting"},{"key":"coats","text_en":"Minimum 2 coats, full coverage including reveals"},{"key":"sanding","text_en":"Sanded with lamp check — no scratches, pits or joints visible"}]',
 '["Raking-light inspection passed on 100% of surfaces","All MEP boxes masked, not filled over"]',
 '["pls_cure","gyp_taping"]',
 '["wall_putty","sandpaper"]',
 '[{"key":"lamp_check","description_en":"Raking-light check on puttied walls","min_count":3}]',
 '["Random scrape adhesion check","Edges and arrises still crisp, not rounded by sanding"]'),

('painting','pnt_primer','Primer / Sealer','البرايمر',2,15.00,
 'Apply pigmented primer-sealer to all puttied surfaces to unify absorption and reveal remaining defects.',
 '[{"key":"coverage","text_en":"Uniform single coat, no misses (check against raw putty color)"},{"key":"defect_pass","text_en":"Defects highlighted by primer re-filled and re-primed"}]',
 '["No suction differences visible when half-dry","Surfaces dust-free after final sand"]',
 '["pnt_putty"]',
 '["primer_sealer"]',
 '[{"key":"primed","description_en":"Primed rooms","min_count":2}]',
 '["Primer compatible with topcoat system","No primer on hardware/glass (masking intact)"]'),

('painting','pnt_first','First Coat','الوجه الأول',3,25.00,
 'Apply first finish coat in approved colors; cut lines at ceilings and color changes.',
 '[{"key":"color","text_en":"Colors match approved schedule per room (verify code on can)"},{"key":"cut_lines","text_en":"Straight cut lines at ceiling and feature walls"},{"key":"film","text_en":"Even film, no runs/roller marks after leveling"}]',
 '["Full coverage, minor grinning acceptable before final coat only"]',
 '["pnt_primer"]',
 '["emulsion_paint"]',
 '[{"key":"first_coat","description_en":"First-coated rooms","min_count":2}]',
 '["Wet film thickness spot check","Ventilation during application"]'),

('painting','pnt_final','Final Coat & Touch-ups','الوجه الأخير واللمسات',4,30.00,
 'Apply final coat after all wet/dusty trades finish; touch up after accessory and carpentry installation.',
 '[{"key":"sequence","text_en":"Applied AFTER tiling, gypsum, and carpentry sanding are complete"},{"key":"finish","text_en":"Uniform sheen, no patchiness under daylight and artificial light"},{"key":"touchup","text_en":"Post-fit-out touch-ups blended, not patch-visible"}]',
 '["Client-light inspection (day + night) passed","Leftover labeled paint (min 1L per color) handed to client"]',
 '["pnt_first","flr_grout_skirt","car_doors"]',
 '["emulsion_paint"]',
 '[{"key":"final","description_en":"Finished rooms both lighting conditions","min_count":4}]',
 '["Sheen uniformity at grazing angles","Cut lines at cove lighting edges perfect (light magnifies)"]'),

-- ----------------------------------------------------------------- carpentry
('carpentry','car_frames','Door Frames Installation','تركيب حلوق الأبواب',1,20.00,
 'Install door frames plumb/square, anchored and foamed, before final plaster/paint interfaces.',
 '[{"key":"plumb","text_en":"Frames plumb both axes <= 2 mm; diagonals equal"},{"key":"height","text_en":"Head height uniform across floor (laser)"},{"key":"anchors","text_en":"Min 3 anchors per jamb + PU foam continuous"},{"key":"protection","text_en":"Frames wrapped until final paint"}]',
 '["Opening sizes leave 3-4 mm leaf gaps","Wet-area frames are WPC/aluminum or fully sealed"]',
 '["pls_plaster"]',
 '["door_frames","pu_foam","anchors"]',
 '[{"key":"frames","description_en":"Installed frames with level on jamb","min_count":3}]',
 '["Frame material vs room type (no MDF in bathrooms)","Floor finish thickness accounted in frame height"]'),

('carpentry','car_doors','Door Leaves & Hardware','تركيب ضلف الأبواب والإكسسوارات',2,30.00,
 'Hang leaves, fit locks/hinges/stoppers, align gaps, adjust closing action.',
 '[{"key":"gaps","text_en":"Even 3 mm gaps at head/sides; 8-10 mm floor clearance (more if carpet)"},{"key":"hardware","text_en":"Locks latch smoothly; keys/cards handed over labeled"},{"key":"stoppers","text_en":"Door stoppers placed — no handle hits a wall"},{"key":"swing","text_en":"Swing direction matches layout (into rooms, not blocking switches)"}]',
 '["Every door closes with soft push, no scraping","Privacy locks on bathrooms/bedrooms function"]',
 '["car_frames","flr_tiling"]',
 '["door_leaves","hinges","locksets","stoppers"]',
 '[{"key":"doors","description_en":"Hung doors closed, gap lines visible","min_count":4}]',
 '["Hinge screws full-set, not partial","Handle height uniform 100-105 cm","Door undercut allows return air where AC design requires"]'),

('carpentry','car_wardrobes','Wardrobes & Built-ins','تركيب الدواليب والخزائن',3,25.00,
 'Install wardrobes, vanities and built-ins: leveled carcasses, aligned fronts, adjusted hardware.',
 '[{"key":"level","text_en":"Carcasses leveled at base (laser) before joining"},{"key":"scribe","text_en":"Filler panels scribed to walls/ceiling — no open gaps"},{"key":"alignment","text_en":"Door/drawer fronts co-planar, equal reveals"},{"key":"anchoring","text_en":"Tall units anchored to wall (tip-over)"}]',
 '["All drawers/doors operate silently full-travel","Soft-close engaged on all fronts","Interiors clean, protective film removed"]',
 '["pnt_first","flr_tiling"]',
 '["wardrobe_units","hardware"]',
 '[{"key":"builtin","description_en":"Installed units open + closed","min_count":3}]',
 '["Back panels don''t trap sockets — cutouts with access","Hanging rail heights per standard (100/200 cm double hang)"]'),

('carpentry','car_kitchen','Kitchen Installation','تركيب المطبخ',4,25.00,
 'Install kitchen cabinets, countertop templating/fitting, appliance integration, final sealing.',
 '[{"key":"level","text_en":"Base run level within 2 mm over full length"},{"key":"services","text_en":"Cutouts for sink/hob/services precise; edges sealed"},{"key":"counter","text_en":"Countertop seams tight, silicone at wall junction"},{"key":"appliances","text_en":"Appliances fitted, doors aligned, ventilation gaps per spec"}]',
 '["Sink/hob/dishwasher operational after install","Water test under sink 24h dry","All shelves/accessories delivered"]',
 '["plb_supply_rough","ele_accessories","flr_tiling","pnt_first"]',
 '["kitchen_cabinets","countertop","appliances"]',
 '[{"key":"kitchen","description_en":"Finished kitchen: fronts, counter, appliances","min_count":4}]',
 '["Hob-to-hood distance 65-75 cm","Cutout edges in worktop sealed against swelling","Anti-tip brackets on tall oven housings"]'),

-- ------------------------------------------------------------------ lighting
('lighting','lgt_install','Fixtures Installation','تركيب وحدات الإضاءة',1,50.00,
 'Install downlights, strips, pendants and feature fixtures per lighting layout after final paint.',
 '[{"key":"positions","text_en":"Fixture positions match layout (spacing/wall offset per standard)"},{"key":"strips","text_en":"LED strips continuous, drivers accessible, no visible dots/joints in coves"},{"key":"pendants","text_en":"Pendants centered on furniture positions at spec heights"},{"key":"anchors","text_en":"Chandeliers on rated anchors to slab, not to gypsum"}]',
 '["Every fixture from layout installed and lit","Consistent color temperature within each room (verify bin/CCT)"]',
 '["ele_accessories","pnt_final"]',
 '["downlights","led_strips","decorative_fixtures","drivers"]',
 '[{"key":"lit_rooms","description_en":"Each room with all layers on","min_count":4}]',
 '["Mixed CCT check (one 4000K spot in a 3000K room is a snag)","Cove strip visible-dot check at eye level","Driver hum test in silent room"]'),

('lighting','lgt_smart','Smart System Programming','برمجة النظام الذكي',2,20.00,
 'Commission smart switches/hub, create scenes, bind sensors, hand over app access.',
 '[{"key":"binding","text_en":"All smart devices joined to hub, named per room (AR + EN)"},{"key":"scenes","text_en":"Agreed scenes programmed (welcome/away/night/movie)"},{"key":"sensors","text_en":"Motion sensor zones and timeouts configured"},{"key":"fallback","text_en":"Physical switches still operate lights if hub offline"}]',
 '["Client app account is owner (not installer account)","Scene walkthrough done with client"]',
 '["lgt_install"]',
 '["smart_hub"]',
 '[{"key":"app","description_en":"App dashboard showing all rooms online","min_count":1}]',
 '["Hub offline test — manual control works","Naming matches room signage/drawings"]'),

('lighting','lgt_test','Focusing, Testing & Handover','التوجيه والفحص والتسليم',3,30.00,
 'Aim adjustable fixtures, verify lux levels against standards, resolve snags, complete photometric handover.',
 '[{"key":"lux","text_en":"Lux measured at working plane per room vs kb_lighting_standards"},{"key":"aiming","text_en":"Adjustable spots aimed at art/features, not into eyes/screens"},{"key":"dimming","text_en":"Dimming smooth full-range, no flicker at low end"},{"key":"labels","text_en":"Switch functions labeled/explained to client"}]',
 '["Measured lux within min-max band in every room","Zero flickering fixtures (slow-mo phone camera test)","Snag list closed"]',
 '["lgt_install","lgt_smart"]',
 '[]',
 '[{"key":"lux_meter","description_en":"Lux meter readings in key rooms","min_count":3}]',
 '["Flicker test on all dimmed circuits","Verify IP-rated fittings actually installed in wet zones","Emergency/night pathways acceptable"]');
