-- Facts vocabulary. The admin-panel rule builder renders its "field" dropdown
-- from this table, so adding a fact here (plus supplying it in the engine's
-- fact payload) is all that is needed to make a new condition composable by a
-- business user — no code deploy.
SET NAMES utf8mb4;

INSERT IGNORE INTO kb_facts (fact_code, label_en, label_ar, data_type, unit, allowed_values, domain, description_en) VALUES
-- room / general
('roomType','Room Type','نوع الغرفة','enum',NULL,
 '["master_bedroom","bedroom","kids_room","guest_room","dressing_room","living_room","family_room","dining_room","majlis","office","kitchen","bathroom","guest_bathroom","laundry","maid_room","driver_room","storage","entrance","corridor","staircase","balcony"]',
 'room','Room type code from kb_room_types.'),
('area','Room Area','مساحة الغرفة','number','m2',NULL,'room','Net floor area.'),
('length','Room Length','طول الغرفة','number','m',NULL,'room','Longest internal dimension.'),
('width','Room Width','عرض الغرفة','number','m',NULL,'room','Shortest internal dimension.'),
('ceilingHeight','Ceiling Height','ارتفاع السقف','number','m',NULL,'room','Finished floor to finished ceiling.'),
('windowCount','Window Count','عدد النوافذ','number','count',NULL,'room',NULL),
('doorCount','Door Count','عدد الأبواب','number','count',NULL,'room',NULL),
('hasExternalWall','Has External Wall','يحتوي جدار خارجي','boolean',NULL,NULL,'room',NULL),
('isWetArea','Is Wet Area','منطقة رطبة','boolean',NULL,NULL,'room',NULL),
('finishLevel','Finish Level','مستوى التشطيب','enum',NULL,'["economy","standard","premium","luxury"]','general','Project finishing tier — drives recommendation depth.'),
('occupantType','Occupant Type','نوع الساكن','enum',NULL,'["family","couple","single","kids","elderly","staff","guest"]','general',NULL),
('unitType','Unit Type','نوع الوحدة','enum',NULL,'["apartment","villa","duplex","studio","office"]','general',NULL),

-- lighting
('lightingLux','Designed Lux Level','مستوى الإضاءة المصمم','number','lux',NULL,'lighting','Calculated average lux at working plane.'),
('spotlightCount','Spotlight Count','عدد السبوت لايت','number','count',NULL,'lighting',NULL),
('spotlightSpacing','Spotlight Spacing','تباعد السبوت لايت','number','cm',NULL,'lighting','Average center-to-center spacing.'),
('hasHiddenLed','Has Hidden LED','يوجد إضاءة مخفية','boolean',NULL,NULL,'lighting',NULL),
('lightingZones','Lighting Zones','عدد مناطق الإضاءة','number','count',NULL,'lighting','Independently switched groups.'),
('hasDimmer','Has Dimmer','يوجد دimmer','boolean',NULL,NULL,'lighting',NULL),
('switchCount','Switch Count','عدد المفاتيح','number','count',NULL,'lighting',NULL),
('hasTwoWaySwitch','Has Two-way Switch','يوجد مفتاح مزدوج','boolean',NULL,NULL,'lighting',NULL),
('colorTempK','Color Temperature','درجة حرارة اللون','number','K',NULL,'lighting',NULL),
('cri','Color Rendering Index','معامل إظهار الألوان','number','CRI',NULL,'lighting',NULL),
('fixtureIpRating','Fixture IP Rating','تصنيف الحماية IP','number',NULL,NULL,'lighting','Numeric form, e.g. 44 for IP44.'),
('hasMirrorLight','Has Mirror Lighting','إضاءة المرآة','boolean',NULL,NULL,'lighting',NULL),
('hasTaskLight','Has Task Lighting','إضاءة مهام','boolean',NULL,NULL,'lighting','Under-cabinet, desk, or vanity task layer.'),

-- electrical
('socketCount','Socket Count','عدد الأفياش','number','count',NULL,'electrical',NULL),
('tvPointCount','TV Point Count','عدد نقاط التلفاز','number','count',NULL,'electrical',NULL),
('internetPointCount','Internet Point Count','عدد نقاط الإنترنت','number','count',NULL,'electrical',NULL),
('acPointCount','AC Point Count','عدد نقاط التكييف','number','count',NULL,'electrical',NULL),
('usbPointCount','USB Point Count','عدد نقاط USB','number','count',NULL,'electrical',NULL),
('smartPointCount','Smart Home Point Count','عدد نقاط المنزل الذكي','number','count',NULL,'electrical',NULL),
('socketHeight','Socket Height','ارتفاع الفيش','number','cm',NULL,'electrical','From finished floor level.'),
('hasRcd','Has RCD/GFCI Protection','يوجد قاطع تسرب أرضي','boolean',NULL,NULL,'electrical',NULL),
('hasDedicatedCircuit','Has Dedicated Circuit','دائرة مستقلة','boolean',NULL,NULL,'electrical',NULL),
('cableSizeMm2','Cable Size','مقطع الكابل','number','mm2',NULL,'electrical',NULL),
('breakerAmp','Breaker Rating','أمبير القاطع','number','A',NULL,'electrical',NULL),
('applianceLoadKw','Appliance Load','حمل الأجهزة','number','kW',NULL,'electrical',NULL),
('socketToWaterDistance','Socket-to-Water Distance','بعد الفيش عن مصدر الماء','number','cm',NULL,'electrical','Horizontal distance to nearest water source.'),
('counterLengthM','Counter Length','طول الكاونتر','number','m',NULL,'electrical','Kitchen worktop run length.'),

-- plumbing
('wcCount','WC Count','عدد الكراسي','number','count',NULL,'plumbing',NULL),
('basinCount','Basin Count','عدد المغاسل','number','count',NULL,'plumbing',NULL),
('showerCount','Shower Count','عدد الدشات','number','count',NULL,'plumbing',NULL),
('floorDrainCount','Floor Drain Count','عدد الصفايات','number','count',NULL,'plumbing',NULL),
('hasShattaf','Has Hand Spray Point','يوجد شطاف','boolean',NULL,NULL,'plumbing',NULL),
('hasWaterHeater','Has Water Heater','يوجد سخان','boolean',NULL,NULL,'plumbing',NULL),
('hasHeaterDrainPan','Heater Drain Pan Piped','حوض تصريف السخان موصول','boolean',NULL,NULL,'plumbing',NULL),
('hasAccessPanel','Has Access Panel','يوجد فتحة صيانة','boolean',NULL,NULL,'plumbing',NULL),
('hasWaterproofing','Has Waterproofing','يوجد عزل مائي','boolean',NULL,NULL,'plumbing',NULL),
('waterproofUpstandCm','Waterproofing Upstand','ارتفاع العزل على الجدار','number','cm',NULL,'plumbing',NULL),
('floorSlopePct','Floor Slope','ميل الأرضية','number','%',NULL,'plumbing',NULL),
('wcSideClearance','WC Side Clearance','خلوص الكرسي الجانبي','number','cm',NULL,'plumbing','Centerline to wall/fixture.'),
('wcFrontClearance','WC Front Clearance','خلوص الكرسي الأمامي','number','cm',NULL,'plumbing',NULL),
('showerWidthCm','Shower Width','عرض الدش','number','cm',NULL,'plumbing',NULL),
('showerDepthCm','Shower Depth','عمق الدش','number','cm',NULL,'plumbing',NULL),
('hasHotSupply','Has Hot Water Supply','يوجد ماء ساخن','boolean',NULL,NULL,'plumbing',NULL),
('hasVentFan','Has Exhaust Fan','يوجد شفاط','boolean',NULL,NULL,'plumbing',NULL),
('drainDiameterMm','Drain Diameter','قطر الصرف','number','mm',NULL,'plumbing',NULL),

-- furniture
('bedSize','Bed Size','مقاس السرير','enum',NULL,'["single","double","queen","king","bunk"]','furniture',NULL),
('bedSideClearance','Bed Side Clearance','خلوص جانب السرير','number','cm',NULL,'furniture',NULL),
('bedFootClearance','Bed Foot Clearance','خلوص نهاية السرير','number','cm',NULL,'furniture',NULL),
('wardrobeWidthCm','Wardrobe Width','عرض الدولاب','number','cm',NULL,'furniture',NULL),
('wardrobeClearance','Wardrobe Door Clearance','خلوص باب الدولاب','number','cm',NULL,'furniture',NULL),
('circulationWidth','Circulation Width','عرض ممر الحركة','number','cm',NULL,'furniture','Narrowest walking path in the layout.'),
('tableToWallCm','Table-to-Wall Distance','بعد الطاولة عن الجدار','number','cm',NULL,'furniture',NULL),
('sofaToTableCm','Sofa-to-Coffee-Table Distance','بعد الكنبة عن الطاولة','number','cm',NULL,'furniture',NULL),
('tvViewingDistanceM','TV Viewing Distance','مسافة مشاهدة التلفاز','number','m',NULL,'furniture',NULL),
('tvSizeInch','TV Size','مقاس التلفاز','number','inch',NULL,'furniture',NULL),
('seatCount','Seat Count','عدد المقاعد','number','count',NULL,'furniture',NULL),
('deskClearance','Desk Chair Clearance','خلوص كرسي المكتب','number','cm',NULL,'furniture',NULL),
('furnitureCount','Furniture Item Count','عدد قطع الأثاث','number','count',NULL,'furniture',NULL),
('furnitureAreaRatio','Furniture Area Ratio','نسبة إشغال الأثاث','number','ratio',NULL,'furniture','Furniture footprint ÷ room area.'),

-- finishing
('flooringCategory','Flooring Category','نوع الأرضية','enum',NULL,'["porcelain","ceramic","natural_stone","vinyl","wood","epoxy"]','finishing',NULL),
('flooringWetSuitable','Flooring Wet-area Suitable','الأرضية مناسبة للمناطق الرطبة','boolean',NULL,NULL,'finishing',NULL),
('paintCategory','Paint Type','نوع الدهان','enum',NULL,'["emulsion","specialty","enamel","texture"]','finishing',NULL),
('paintWashable','Paint Is Washable','دهان قابل للغسيل','boolean',NULL,NULL,'finishing',NULL),
('ceilingCategory','Ceiling Type','نوع السقف','enum',NULL,'["gypsum","pvc","acoustic","stretch"]','finishing',NULL),
('ceilingMoistureResistant','Moisture-resistant Ceiling Board','لوح سقف مقاوم للرطوبة','boolean',NULL,NULL,'finishing',NULL),
('doorCategory','Door Type','نوع الباب','enum',NULL,'["wood_solid","mdf","hdf","wpc","aluminum","glass","steel"]','finishing',NULL),
('materialCostCategory','Material Cost Category','فئة تكلفة المادة','enum',NULL,'["economy","standard","premium","luxury"]','finishing',NULL),
('materialDurability','Material Durability','متانة المادة','enum',NULL,'["low","medium","high","very_high"]','finishing',NULL),
('maintenanceLevel','Maintenance Level','مستوى الصيانة','enum',NULL,'["low","medium","high"]','finishing',NULL),
('tileSizeCm','Tile Size','مقاس البلاط','number','cm',NULL,'finishing','Longest edge.'),
('hasAntiSlip','Has Anti-slip Rating','مقاوم للانزلاق','boolean',NULL,NULL,'finishing',NULL),

-- progress
('stageCode','Stage Code','كود المرحلة','string',NULL,NULL,'progress',NULL),
('stageProgressPct','Stage Progress','نسبة إنجاز المرحلة','number','%',NULL,'progress',NULL),
('photoCount','Uploaded Photo Count','عدد الصور المرفوعة','number','count',NULL,'progress',NULL),
('checklistCompletePct','Checklist Completion','نسبة إكمال قائمة الفحص','number','%',NULL,'progress',NULL),
('dependenciesComplete','Dependencies Complete','المراحل السابقة مكتملة','boolean',NULL,NULL,'progress',NULL),
('inspectionPassed','Inspection Passed','اجتاز الفحص','boolean',NULL,NULL,'progress',NULL),
('daysSinceLastUpdate','Days Since Last Update','أيام منذ آخر تحديث','number','day',NULL,'progress',NULL),
('pressureTestPassed','Pressure Test Passed','اجتاز اختبار الضغط','boolean',NULL,NULL,'progress',NULL),
('floodTestPassed','Flood Test Passed','اجتاز اختبار الغمر','boolean',NULL,NULL,'progress',NULL),
('moistureContentPct','Substrate Moisture','رطوبة السطح','number','%',NULL,'progress',NULL);
