/**
 * Branded identifiers and UUIDv7 generation.
 *
 * WHY BRANDED: `function assign(unitId: string, userId: string)` accepts the
 * arguments in the wrong order and compiles. With branded types it does not.
 * Given how many identifiers this domain carries — company, project, unit,
 * room, stage, material, movement — that mistake is inevitable otherwise.
 *
 * WHY UUIDv7: auto-increment leaks tenant volume (`/units/1841` tells a
 * competitor the row count), cannot be generated by an offline mobile client,
 * and complicates sharding. UUIDv4 is random, which destroys InnoDB clustered
 * index insert locality at write volume. UUIDv7 puts a millisecond timestamp in
 * the high bits, so inserts stay sequential while remaining globally unique and
 * generatable on a phone with no signal. docs/18 ADR-005
 */

declare const brand: unique symbol

export type Branded<T, B extends string> = T & { readonly [brand]: B }

export type CompanyId = Branded<string, 'CompanyId'>
export type UserId = Branded<string, 'UserId'>
export type ClientId = Branded<string, 'ClientId'>
export type ProjectId = Branded<string, 'ProjectId'>
export type UnitId = Branded<string, 'UnitId'>
export type RoomId = Branded<string, 'RoomId'>
export type UnitStageId = Branded<string, 'UnitStageId'>
export type UnitWorkflowId = Branded<string, 'UnitWorkflowId'>
export type MaterialId = Branded<string, 'MaterialId'>
export type StockMovementId = Branded<string, 'StockMovementId'>
export type BoqId = Branded<string, 'BoqId'>
export type DocumentId = Branded<string, 'DocumentId'>
export type EventId = Branded<string, 'EventId'>

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

export const isUuid = (value: string): boolean => UUID_RE.test(value)

/**
 * Casts a validated string to a branded id.
 *
 * Rejects malformed input rather than trusting it: ids arrive from URLs, from
 * mobile clients, and from sync payloads, and a malformed one must not reach a
 * query.
 */
export function toId<B extends string>(value: string): Branded<string, B> {
  if (!isUuid(value)) throw new TypeError(`Not a valid UUID: ${value}`)
  return value as Branded<string, B>
}

/**
 * Port for id generation.
 *
 * Injected rather than imported so tests can produce deterministic ids — a
 * domain test asserting on a generated id is otherwise unwritable, and
 * `Math.random` is banned in the domain layer by lint. docs/06 §1
 */
export interface IdGenerator {
  next<B extends string>(): Branded<string, B>
}

/**
 * UUIDv7: 48-bit big-endian millisecond timestamp, 4-bit version, 12 bits of
 * randomness, 2-bit variant, 62 bits of randomness.
 *
 * The monotonic counter matters: several entities are frequently created within
 * the same millisecond (a stage set of 14, a BOQ of 147 lines). Without it,
 * their ids would sort arbitrarily within that millisecond and lose the insert
 * locality that motivated choosing v7.
 */
export class Uuid7Generator implements IdGenerator {
  #lastMs = 0
  #counter = 0

  constructor(private readonly now: () => number = () => Date.now()) {}

  next<B extends string>(): Branded<string, B> {
    const ms = this.now()
    if (ms === this.#lastMs) {
      this.#counter++
    } else {
      this.#lastMs = ms
      this.#counter = 0
    }

    const bytes = new Uint8Array(16)
    // 48-bit timestamp, big-endian
    bytes[0] = (ms / 2 ** 40) & 0xff
    bytes[1] = (ms / 2 ** 32) & 0xff
    bytes[2] = (ms / 2 ** 24) & 0xff
    bytes[3] = (ms / 2 ** 16) & 0xff
    bytes[4] = (ms / 2 ** 8) & 0xff
    bytes[5] = ms & 0xff

    const random = crypto.getRandomValues(new Uint8Array(10))
    bytes.set(random, 6)

    // Sequence counter occupies rand_a so same-millisecond ids stay ordered:
    // the version nibble takes the top 4 bits and the counter keeps the rest.
    bytes[6] = 0x70 | ((this.#counter >> 8) & 0x0f) // version 7 + counter high
    bytes[7] = this.#counter & 0xff
    bytes[8] = ((bytes[8] ?? 0) & 0x3f) | 0x80 // RFC 4122 variant

    const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('')
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}` as Branded<
      string,
      B
    >
  }
}

/** Deterministic generator for tests. Produces valid, ordered UUIDv7 values. */
export class SequentialIdGenerator implements IdGenerator {
  #n = 0
  constructor(private readonly seedMs = 1_700_000_000_000) {}

  next<B extends string>(): Branded<string, B> {
    const ms = this.seedMs + this.#n++
    const hex = ms.toString(16).padStart(12, '0')
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-7000-8000-${this.#n
      .toString(16)
      .padStart(12, '0')}` as Branded<string, B>
  }
}
